name: ruah
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  syncfusion_flutter_pdfviewer: ^24.2.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.6
  http: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - cantosDoc/
    - cantosDoc/Adoracion/
    - cantosDoc/Adviento/
    - cantosDoc/Agradecimiento/
    - cantosDoc/Alabanza/
    - cantosDoc/Aleluya/
    - cantosDoc/Bautismo/
    - cantosDoc/Boda/
    - cantosDoc/Comunion/
    - cantosDoc/Cordero/
    - cantosDoc/Curesma/
    - cantosDoc/Difunto/
    - cantosDoc/Entrada/
    - cantosDoc/Espiritu/
    - cantosDoc/Navidad/
    - cantosDoc/Ofertorio/
    - cantosDoc/Pascua/
    - cantosDoc/Reflexion/
    - cantosDoc/Salida/
    - cantosDoc/Santo/
    - cantosDoc/Villancico/