name: cancionero
description: Este proyecto pone en práctica la integración de Firebase. Permite la visualización de cantos por categoría, búsqueda por nombre de canto y operaciones CRUD básicas utilizando Firebase Realtime Database y Firebase Storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  syncfusion_flutter_pdfviewer: ^24.2.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.6
  http: ^1.2.0
  remove_diacritic: ^0.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - imagenes/